### ISSUE TITLE
waiting for comments to load

### ISSUE THREAD

**Issue by mesutsarikan** [kennethkn/instagram-activities-wipe#4]
i did it and its open my chrome and insta and then comment settings and i can see  all the comments in my screen
but scripts keep givin info how can i fix it  INFO] instagram-comments-wipe: Waiting for comments to load...
![image](https://github.com/kennethkn/instagram-activities-wipe/assets/166408632/3baf8fda-d954-43e0-9a49-72ac02371cf2)

**Comment by Indratejreddy** [comment]
if the script add one comment after deleting 100 comments and refresh the page it should fix the issue

**Comment by mesutsarikan** [comment]
its not deleted even one comment so just waiting for comments but noting
happen is it about google driver couse in github page you write the os
commends and im using windows how can i install goodledriver in win10 if
this is the problem thank you


13 Nis 2024 Cmt 10:02 tarihinde Indratej Reddy ***@***.***>
şunu yazdı:
