### ISSUE TITLE
I have chromedriver installed but is says I don't?

### ISSUE THREAD

**Issue by kitttwilight** [kennethkn/instagram-activities-wipe#5]
[ERROR] instagram-comments-wipe: Web driver could not start. Have you installed ChromeDriver? Check README for details

Please help! Thank you so much

**Comment by kennethkn** [comment]
Hello, thanks for trying out the script. To help you debug, I have a few questions: 
- Are you on Windows, Linux, or macOS?
- Have you installed Chrome? You need both Chrome and ChromeDriver.
- Can you see a folder created by the script, named `chrome-profile`?
