### ISSUE TITLE
Doesn't seem to work to delete the comments

### ISSUE THREAD

**Issue by Dokukanal** [kennethkn/instagram-activities-wipe#6]
When I enter "1", it tries to search for the likes! Nothing happens. 
If I enter "2", the same thing happens.

![grafik](https://github.com/kennethkn/instagram-activities-wipe/assets/166512533/9b29fdc4-1a79-4c85-811c-8503e18135e7)

In addition:
[28172:17740:0505/100245.445:ERROR:sandbox_win.cc(895)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: Zugriff verweigert (0x5)
![grafik](https://github.com/kennethkn/instagram-activities-wipe/assets/166512533/f996d77e-6946-4d27-8970-0d31edb271c0)

**Comment by kennethkn** [comment]
Hello, thanks for using the script. The issue has been resolved. There was a typo in the script when I pushed an update earlier.

**Comment by Dokukanal** [comment]
Thank you, he now selects the correct option.
