### ISSUE TITLE
Sandbox cannot access executable

### ISSUE THREAD

**Issue by Dokukanal** [kennethkn/instagram-activities-wipe#7]
[28172:17740:0505/100245.445:ERROR:sandbox_win.cc(895)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: Zugriff verweigert (0x5)
![328002119-f996d77e-6946-4d27-8970-0d31edb271c0](https://github.com/kennethkn/instagram-activities-wipe/assets/166512533/a73759c9-bb65-4f07-ba4c-be4e143f947f)

It loads and loads, but does not delete anything.

**Edit:**
Windows 11 (D:\instagram-activities-wipe-master)
All users have full access

**Comment by kennethkn** [comment]
There might be something wrong with your installation of Chrome. Did a new Chrome instance appear on your screen?

**Comment by Dokukanal** [comment]
![grafik](https://github.com/kennethkn/instagram-activities-wipe/assets/166512533/b51cbf89-764c-43f5-b6f5-6cba3d093491)
It is the version that was downloaded from the script here.

**Comment by kennethkn** [comment]
Oh I know what's happening. My script is not multilingual. If you switch the language to English, it will work.

**Comment by Dokukanal** [comment]
Ok, no problem. I'll test it again later and give you feedback. Many thanks for your work!
I'm looking forward to more great tools that fulfill exactly these purposes!

**Comment by Dokukanal** [comment]
Works perfectly.
I recommend including this in the description.

**Comment by kennethkn** [comment]
Thanks for your suggestion. Added :)
